//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankside.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string surname { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string card_Type { get; set; }
        public string currency { get; set; }
        public string Card_Number { get; set; }
        public Nullable<decimal> Total_Balance { get; set; }
        public string Card_Expiration { get; set; }
        public Nullable<int> Card_cvv { get; set; }
        public Nullable<System.DateTime> Payment_date { get; set; }
    }
}
